In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv('insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [6]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
cols_to_impute = [i for i in range(X.shape[1]) if i not in [1,4,5]]
imputer.fit(X[:, cols_to_impute])
X[:, cols_to_impute] = imputer.transform(X[:, cols_to_impute])

In [10]:
print(X)

[[19.0 'female' 27.9 0.0 'yes' 'southwest']
 [18.0 'male' 33.77 1.0 'no' 'southeast']
 [28.0 'male' 33.0 3.0 'no' 'southeast']
 ...
 [18.0 'female' 36.85 0.0 'no' 'southeast']
 [21.0 'female' 25.8 0.0 'no' 'southwest']
 [61.0 'female' 29.07 0.0 'yes' 'northwest']]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,5])],
                       remainder='passthrough')
X=ct.fit_transform(X)
print(X)


[[1.0 0.0 0.0 ... 19.0 27.9 0.0]
 [0.0 1.0 1.0 ... 18.0 33.77 1.0]
 [0.0 1.0 1.0 ... 28.0 33.0 3.0]
 ...
 [1.0 0.0 1.0 ... 18.0 36.85 0.0]
 [1.0 0.0 1.0 ... 21.0 25.8 0.0]
 [1.0 0.0 0.0 ... 61.0 29.07 0.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[1005   57  306 ...   32   91 1171]


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
print(X_train)

[[1.0 0.0 1.0 ... 53.0 26.6 0.0]
 [0.0 1.0 1.0 ... 53.0 21.4 1.0]
 [0.0 1.0 1.0 ... 18.0 37.29 0.0]
 ...
 [1.0 0.0 0.0 ... 51.0 34.96 2.0]
 [1.0 0.0 0.0 ... 40.0 22.22 2.0]
 [0.0 1.0 1.0 ... 57.0 27.94 1.0]]


In [28]:
print(X_test)

[[0.0 1.0 1.0 ... 19.0 35.53 0.0]
 [0.0 1.0 1.0 ... 57.0 31.54 0.0]
 [0.0 1.0 1.0 ... 51.0 37.0 0.0]
 ...
 [0.0 1.0 0.0 ... 47.0 38.94 2.0]
 [1.0 0.0 1.0 ... 19.0 36.575 0.0]
 [1.0 0.0 1.0 ... 35.0 26.125 0.0]]


In [29]:
print(y_train)

[ 730  712    6 ... 1298 1052  813]


In [30]:
print(y_test)

[  42  794  631  732   98 1242  665  817  195 1056  881  811  451  504
    5  644 1097  460 1164  926  691 1265  571  602  116  479  622  591
  386  241  819  822 1133 1190 1122  700 1220 1023  834 1252  293  825
 1060  866  354 1178 1160 1199  688  963  875  836  133  650 1010  267
 1266  884 1102    8  218  910 1031  162  888  629  726 1099  165  973
 1334 1333   63  871  917 1268  175  182  774  739  198  863  764   86
 1246 1276  501 1306  731  562 1068 1121  943  637   31  675  699  861
  859  458  795  988 1029 1200 1153 1024   62  538  123  788  299  264
   35  986  878   14  480  955 1053  128  640  753  425  508 1288  680
  905 1050 1289  560 1217   71  507 1236 1129   61   36   34  710  565
  950  420 1042  958  930  745   55  566   58  481  511  256 1187  835
  564  422  709  708  674   70  244 1329  843  186  436   23 1240  736
  775  397  369  233 1103 1142  217  469  138  974  245  415  887  931
  646  553  239 1028  109  615  545  656  951 1313  210  164  496  659
  522 

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
print(X_train)

[[ 1.01886959 -1.01886959  0.50874702 ...  1.00228629 -0.66474472
  -0.90705771]
 [-0.98147988  0.98147988  0.50874702 ...  1.00228629 -1.51402369
  -0.07894188]
 [-0.98147988  0.98147988  0.50874702 ... -1.50426607  1.08117685
  -0.90705771]
 ...
 [ 1.01886959 -1.01886959 -1.96561348 ...  0.85905473  0.70063454
   0.74917395]
 [ 1.01886959 -1.01886959 -1.96561348 ...  0.07128113 -1.38009893
   0.74917395]
 [-0.98147988  0.98147988  0.50874702 ...  1.28874942 -0.44589206
  -0.07894188]]


In [ ]:
print(X_tes)